server:
  port: 9001
spring:
  application:
    name: gateway-sentinel-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 101.37.160.42:8848
        namespace: 7ff27ccd-6a42-4fee-b5ab-5ccb6c7fd54e
        cluster-name: DEFAULT
    sentinel:
      filter:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: application1
          uri: lb://application1
          predicates:
            - Path=/application1/**